### ISSUE TITLE
An onion charge?

### ISSUE THREAD

**Issue by book** [karlwilcox/drawshield-net#10]
I was playing with the language for creating blazons, and noticed the ab sence of an onion in the charges. There are some examples here (some in SVG): <https://commons.wikimedia.org/wiki/Category:Onions_in_heraldry>

**Comment by karlwilcox** [comment]
I have added an onion! Thanks for the suggestion. Also, apologies, the code here is a bit out of date. I will try to get it back in sync with the live version!

**Comment by book** [comment]
Playing with it already!
