### ISSUE TITLE
Fess Positions for Charges does not seem to work.

### ISSUE THREAD

**Issue by PedFastTech** [karlwilcox/drawshield-net#8]
Hi - here is a valid blazon:

Azure a pine tree vert in fess point, a lion's head guardant gold in dexter fess, a lion's head reguardant gold in sinister fess.

However, this won't render. and yields an error:

**> 

> Azure a pine tree vert in fess point a lion's head guardant
> gold in dexter fess a lion's head reguardant gold in sinister
> fess
> Errors:
> parser Do not understand position lions head guardant gold in
> dexter
> blazon Don't understand words in brackets - " Azure a pine
> tree vert in fess point a lions head guardant gold in dexter
> fess a lions head reguardant gold in sinister [fess]"**

Do we have a way of making this work?  Thanks.

**Comment by karlwilcox** [comment]
Hi! I answered this on Google as well - I've used "sinister/dexter flank" rather than "sinister/dexter fess", but you are probably right that sinister/dexter fess should be valid (sinister/dexter/middle chief is, for example). I will add these...

**Comment by PedFastTech** [comment]
Thanks!  Sorry for spamming to Google.  Replacing the word "fess" with "flank" on each charge yields both charges on both sides of the pine tree, overlapped.  See:

![image](https://cloud.githubusercontent.com/assets/18582385/14689489/1ad613fa-070d-11e6-98a1-40f5a7775942.png)

The goal is more like this (done with MSPaint):
![image](https://cloud.githubusercontent.com/assets/18582385/14689584/8eb42500-070d-11e6-8f15-bb1102ca279d.png)

Thanks for such a quick response!  I do say that DrawShield is by far the best heraldry rendering software I've ever seen.

**Comment by karlwilcox** [comment]
Darn! that is a bug. I will take a look and get back to you...

**Comment by karlwilcox** [comment]
Am just trying a few things which make break it for a while...

**Comment by karlwilcox** [comment]
Aha! Try it now...

**Comment by karlwilcox** [comment]
In future John, you can email me at karlwilcox[six squared]@gmail.com - I see that a recent wordpress update has stopped my web page "send me a note" from working. Another fix to do...!

**Comment by PedFastTech** [comment]
Hi - sorry to be even more of a pain, but can it do a lion's head turned to dexter or sinister?

Like this: 

_Azure, a pine tree vert in fess point, a lion's head or to dexter in dexter flank, a lion's head or to sinister in sinister flank_

Guardant and reguardant are sort of that, but it is the head turned against its body when the idea is the two lions guarding the tree.  

Thanks!

**Comment by karlwilcox** [comment]
I have based my lion attitudes on the Wikipedia article [https://en.wikipedia.org/wiki/Lion_(heraldry)](and in fact used the same source images). You can also do "a lions head guardant" which looks to the dexter and "a lions head reguardant" which looks to dexter. (On reflection this is probably wrong, for the whole lion, by default it looks to dexter, reguardant looks to dexter and guardant looks to the front). Anyway, short answer is that we have most of the lions, and their heads in all directions but need to sort out the terminology! I will think about it, but suggestions are welcome!
